#!/bin/bash

# EMAIL CONFIGURATION ----------------------------------------------------------
# put your sendgrid api key here
export SENDGRID_API_KEY='...'

FROM_NAME='Mirco Bertelli'
FROM_ADDR='mirocbe87@no-reply.com'
SUBJECT='corrente ellettrica'
MESSAGE="Ore $(date +%H:%M:%S\ %Z) del $(date +%d/%m/%Y): la corrente è tornata. UPS in modalità rete elettrica."
# comma separated list of email recipients here
TO_ADDR="...,...,..."
# ------------------------------------------------------------------------------

NO_INTERNET=true
COUNTER=60

while [ $NO_INTERNET = true -a $COUNTER -gt 0 ]; do
    COUNTER=$((COUNTER - 1))
    ping -c 1 -W 5 8.8.8.8 &> /dev/null
    if [ $? -eq 0 ]; then
        NO_INTERNET=false
    else
        NO_INTERNET=true
    fi
    sleep 1s
done

if [ $NO_INTERNET = true ]; then
    echo "No internet access"
else
    echo "Internet is came back"
    send-email --from-name "$FROM_NAME" \
               --from-addr "$FROM_ADDR" \
               -s "$SUBJECT" \
               -m "$MESSAGE" \
               -r "$TO_ADDR"
fi

exit 0
